@startuml
participant TestRunner
participant RobotFramework
participant VirtualizationLib
participant OpennessExperienceKits
participant VMs

TestRunner -> RobotFramework: run_tests.sh
activate RobotFramework #FFBBBB

RobotFramework -> RobotFramework: init_environment(json_file)
RobotFramework -> VirtualizationLib: set_environment_config()
activate VirtualizationLib #FFBBBB
deactivate VirtualizationLib

loop for each TestSuite
    RobotFramework -> RobotFramework: run_testsuite()
    activate RobotFramework #DarkSalmon

    RobotFramework -> VirtualizationLib: Clone VM(vm_config)
    activate VirtualizationLib #FFBBBB

    VirtualizationLib --> VMs **: << create >>
    VirtualizationLib -> VMs: create_snapshot('clean')
    note left: 'clean' snapshot will be used only by few tests.
    VirtualizationLib --> RobotFramework: VM Info
    deactivate VirtualizationLib

    RobotFramework --> OpennessExperienceKits **: << clone >>
    RobotFramework -> OpennessExperienceKits: configure()
    activate OpennessExperienceKits #FFBBBB
    deactivate OpennessExperienceKits
    RobotFramework -> OpennessExperienceKits: deploy(vm, OnPrem)
    activate OpennessExperienceKits #FFBBBB
    OpennessExperienceKits -> VMs: deploy(OnPrem)
    activate VMs #FFBBBB
    deactivate OpennessExperienceKits

    RobotFramework -> VirtualizationLib: create_snapshot('deploy')
    activate VirtualizationLib #FFBBBB
    VirtualizationLib -> VMs: create_snapshot('deploy')
    deactivate VirtualizationLib

    loop for each TestCase
        RobotFramework -> VirtualizationLib: revert_to_snapshot('deploy')
        activate VirtualizationLib #FFBBBB
        VirtualizationLib -> VMs: revert_to_snapshot('deploy')
        deactivate VirtualizationLib
        RobotFramework -> VMs: execute_test_steps()
        VMs --> RobotFramework: Test Artifacts
    end

    deactivate VMs

    RobotFramework -> VirtualizationLib: Delete VM
    VirtualizationLib -> VMs !!: delete_vm()
    deactivate RobotFramework
end

RobotFramework --> TestRunner: Test Results

deactivate VMs
deactivate VirtualizationLib
deactivate OpennessExperienceKits
deactivate RobotFramework
@enduml
